apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openviking-data
  namespace: openviking
  labels:
    app: openviking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ibmc-vpc-block-10iops-tier
