apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openviking

resources:
  - 01-namespace.yaml
  - 02-ollama-pvc.yaml
  - 03-ollama-deployment.yaml
  - 04-ollama-service.yaml
  - 05-openviking-secret.yaml
  - 06-openviking-pvc.yaml
  - 07-openviking-deployment.yaml
  - 08-openviking-service.yaml
  - 09-openviking-route.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: openviking
    includeSelectors: false
